project:
  type: website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: []
  navbar:
    background: primary
    search: false
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]